# 6.1 미분이란?

### 1. 기울기

기울기는 x 증가량에 대한 y 증가량으로 정의 된다. 수식은 다음과 같다.

<img src = "기울기1.jpg" width = "300" height = "300">

### 2. 극한(무한소)과 미분

x의 변화량을 매우 작게 만들어 h = x2-x1 에서 h를 0에 가깝게 만들어본다고 가정하면, 

<img src = "극한과미분1.jpg" width = "300" height = "300">

함수 f 위의 지점 (x,f(x))에서의 접선의 기울기 라고 볼 수 있다.

### 3. 도함수

함수 f가 주어졌을 때, 특정 지점 x에 대한 접선의 기울기를 함수로 나타낼 수 있다.

<img src = "도함수2.jpg" width = "300" height = "300">

### 4. 뉴턴 vs 라이프니츠

뉴턴 표기법 : y' = f'(x)
라이프니츠 표기법 : dy/dx = df/dx

### 5. 합성함수 미분

<img src = "합성함수미분1.jpg" width = "300" height = "300">

<img src = "합성함수미분2.jpg" width = "300" height = "300">

# 6.2 편미분

### 1. 편미분

입력 변수가 x,y로 정의되는 함수가 있다고 해보자. z = f(x,y)  
이때, 하나의 입력 변수에 대해서만 미분을 수행할 수 있다. 이것을 편미분이라고 한다. 수식은 다음과 같다.  

<img src = "편미분1.jpg" width = "300" height = "300">

각 미분 결과는 기울기의 크기를 나타낸다. 다변수 함수 f에서 특정지점 (x,y)의 기울기는 각 변수별 미분 결과를 합쳐서 벡터로 나타내게 된다.

<img src = "편미분2.jpg" width = "300" height = "300">

이 기울기 벡터를 그래디언트(gradient)라고 부른다.  
다차원 함수로 정의된 평면에서의 접면의 벡터라고 볼 수 있다.

### 2. 함수의 입출력 형태

벡터를 입력으로 받는 함수  
<img src = "함수의입출력형태1.jpg" width = "300" height = "300">

행렬을 입력으로 받는 함수  
<img src = "함수의입출력형태2.jpg" width = "300" height = "300">

출력이 벡터 또는 행렬인 함수
<img src = "함수의입출력형태3.jpg" width = "300" height = "300">

입력과 출력이 벡터인 함수
<img src = "함수의입출력형태4.jpg" width = "300" height = "300">  
n개의 입력을 받아 m개의 출력을 내보내는 선형 계층도 여기에 속합니다.

### 3. 행렬의 미분

스칼라를 벡터로 미분  
<img src = "행렬의미분1.jpg" width = "300" height = "300">

스칼라를 행렬로 미분
<img src = "행렬의미분2.jpg" width = "300" height = "300">

벡터를 스칼라로 미분  
<img src = "행렬의미분3.jpg" width = "300" height = "300">

벡터를 벡터로 미분
<img src = "행렬의미분4.jpg" width = "300" height = "300">
각 m개의 함수를 벡터 x의 각 n개의 요소로 미분할 경우에 nxm의 행렬 형태로 미분 결과가 나올 것 이다.

# 6.3 경사하강법

알 수 없는 함수 f를 근사계산 하기 위해서 데이터셋 D를 모아 모델 함수가 최적의 출력값을 반환하는(손실함수가 최소가 되는) 모델의 가중치 파라미터 theta^를 찾고 싶다.  
이때 선형계층만을 모델로 활용할 때 수식으로 나타내면 다음과 같다.  
<img src = "경사하강법1.jpg" width = "300" height = "300">  
해당 파라미터를 찾기 위해 가중치 파라미터의 값을 랜덤하게 생성할 순 있으나, 비효율적이다.  
이 때 효율적으로 손실 함수의 출력을 최소로 만드는 입력을 찾기위해 "경사하강법"을 사용한다.

### 1. 1차원에서의 경사하강법

경사하강법은 미분 가능한 복잡한 함수가 있을 때 해당 함수의 최소점을 찾기위한 방법이다.

### 2. 경사하강법의 수식 표현

수식에서 함수 f의 출력 y는 공의 세로축 위치인 높이를 의미한다.  
<img src = "경사하강법의수식표현1.jpg" width = "300" height = "300">

따라서 함수 f의 출력값 y를 미분하면 각 지점에 대한 기울기를 구알 수 있다.  
그다음 움직여야 하는 다음 지점의 위치는 현재 지점의 기울기를 빼면 구할 수 있다. 이 때, 기울기에 상수 n을 곱해주어 움직임의 속도를 제어할 수 있다.  
상수 n을 학습률이라고 부른다.  
이런 식으로 공의 위치를 계속해서 바꿔주다 보면 언젠가는 공이 더 이상 움직일 수 없는 곳에 도달한다.

공의 위치 x에 대응되는 가중치 파라미터 theta는 손실 함수의 출력값을 낮추기 위해서 변경(업데이트) 되어야 한다.  
마찬가지로 손실 함수의 출력값L(theta)은 공의 높이 y에 대응된다.  
손실 함수를 가중치 파라미터로 미분하여 얻은 그래디언트(상수 n을 곱한 후) 현재 가중치 파라미터에서 빼준다.  
<img src = "경사하강법의수식표현2.jpg" width = "300" height = "300">

### 3. 전역 최소점과 지역 최소점

<img src = "전역최소점1.jpg" width = "400" height = "400">

우리가 목표로 하는 지점은 전체 구간에서 가장 낮은 함수의 출력값을 갖는 지점이 된다. 손실 함수를 대입하면 손실 값이 최소가 되는 모델의 가중치 파라미터가 될 것 이다.  
우리는 이 지점을 "전역 최소점"이라고 부른다.  
반대로 녹색 화살표들이 가리키고 있는 지점을 "지역 최소점"이라고 부른다.

경사하강법은 미분 결과를 활용하므로 지역 최소점에 빠질 우려가 있다. 지역 최소점에 빠지게 된다면 더 이상 손실 값을 낮추지 못하고 낮은 성능의 모델을 얻을 가능성도 있다.

### 4. 다차원으로 확장

다음과 같이 2차원 벡터를 입력으로 받는 함수에 대해서 생각해보자.
<img src = "다차원1.jpg" width = "450" height = "450">

마치 다음 그림과 같이 2차원 공간의 평면에서 공을 굴리는 것과 같은 일이 될 것이다.  
공은 그래디언트 화살표와 반대로 굴러간다.
<img src = "다차원2.jpg" width = "400" height = "400">

### 5. 모델 가중치 파라미터로 확장

모델 함수가 선형 계층 함수로 구성되어 있다고 가정한다면 가중치 파라미터를 다음과 같이 정의할 수 있다.
<img src = "모델가중치1.jpg" width = "300" height = "300">

수식에서 볼 수 있듯이 우리는 n*(m+1) 차원 공간에서 최적의 가중치 파라미터를 찾아야 한다.  
이를 위해서 각 가중치 파라미터 W와 b로 손실 함수를 미분하여 그래디언트를 구하고 가중치 파라미터를 업데이트 할 수 있다.
<img src = "모델가중치2.jpg" width = "300" height = "300">

이것을 파라미터 theta로 묶어서 한 번에 표기하면,
<img src = "모델가중치3.jpg" width = "300" height = "300">

# 6.4 학습률에 따른 성질

앞의 수식에서 n으로 표현된 학습률은 보통 0에서 1 사이의 값(사용자에 의해 주어진)을 가진 상수로서 기울기 벡터인 그래디언트에 곱해진다.  
학습률이 0에 가까울수록 파라미터 업데이트의 양은 줄어들 것이고 커질수록 파라미터 업데이트의 양은 늘어난다.  
파라미터가 한 번 업데이트되는 것을 한"스텝" 움직였다 라고 말한다.  
학습률이 클수록 스텝이 크고, 작을수록 스텝이 작다.

<img src = "학습률1.jpg" width = "500" height = "500">

왼쪽 그림은 학습률이 클 때를 나타낸 것이다.  
학습률이 너무 커서 손실 값이 발산해 버리는 상황을 마주할 수 있는데, 학습률을 50% 또는 10%로 줄여주는 것이 좋다.

오른쪽 그림은 학습률이 작을 때를 나타낸 것이다.  
손실 표면이 그림과 같이 울퉁불퉁 굴곡진 상황에서는 자칫 지역최소점에 빠질 수 있다. 또한, 공이 굴러가는 중간에 위치한 평평한 표면에서는 기울기가 0에 가까워져 이동이 더뎌지거나 잘 이동하지 않게 되는 현상에 빠질 수 있다.  
분명한 것은 너무 작은 학습률을 사용하면 기울기가 적게 반영되어 업데이트 되므로 학습이 매우 더디게 될 것 이라는 점이다.  

사용자에 의해 직접 설정되어야 하는 파라미터를 "하이퍼파라미터"라고 부른다.

# 6.5 경사하강법 구현

In [3]:
import torch
import torch.nn.functional as F

In [4]:
# 목표 텐서 생성
target = torch.FloatTensor([[.1,.2,.3],
                            [.4,.5,.6],
                            [.7,.8,.9]])

In [5]:
# 랜덤 값을 갖는 텐서 하나 생성, requires_grad 속성이 True
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

print(x)

tensor([[0.7046, 0.1709, 0.0958],
        [0.4440, 0.8070, 0.3388],
        [0.1025, 0.3848, 0.5676]], requires_grad=True)


In [6]:
# 두 텐서 사이의 손실값 계산
loss = F.mse_loss(x, target)

loss

tensor(0.1347, grad_fn=<MseLossBackward0>)

while 반복문을 사용하여 두 텐서 값의 차이가 변수 threshold의 값보다 작아질 때 까지 미분 및 경사하강법을 반복 수행한다.

In [7]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward() # Calculate gradients.
    
    x = x - learning_rate * x.grad
    
    # You don't need to aware following two lines, now.
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 8.1493e-02
tensor([[0.5703, 0.1773, 0.1412],
        [0.4342, 0.7387, 0.3968],
        [0.2352, 0.4771, 0.6415]], requires_grad=True)
2-th Loss: 4.9298e-02
tensor([[0.4658, 0.1824, 0.1765],
        [0.4266, 0.6857, 0.4420],
        [0.3385, 0.5489, 0.6989]], requires_grad=True)
3-th Loss: 2.9822e-02
tensor([[0.3845, 0.1863, 0.2039],
        [0.4207, 0.6444, 0.4771],
        [0.4189, 0.6047, 0.7436]], requires_grad=True)
4-th Loss: 1.8041e-02
tensor([[0.3213, 0.1893, 0.2253],
        [0.4161, 0.6123, 0.5044],
        [0.4813, 0.6481, 0.7784]], requires_grad=True)
5-th Loss: 1.0913e-02
tensor([[0.2721, 0.1917, 0.2419],
        [0.4125, 0.5874, 0.5257],
        [0.5299, 0.6818, 0.8054]], requires_grad=True)
6-th Loss: 6.6020e-03
tensor([[0.2339, 0.1936, 0.2548],
        [0.4097, 0.5680, 0.5422],
        [0.5677, 0.7081, 0.8264]], requires_grad=True)
7-th Loss: 3.9938e-03
tensor([[0.2041, 0.1950, 0.2648],
        [0.4076, 0.5529, 0.5550],
        [0.5971, 0.7285, 0.8428]], requi

backward 함수를 통해 편미분을 수행한다는 것이 중요하다.  
편미분을 통해 얻어진 그래디언트들이 x.grad에 자동으로 저장되고 이 값을 활용하여 경사하강법을 수행한다.  
참고로 backward를 호출하기 위한 텐서의 크기는 스칼라여야 한다.

# 6.6 파이토치 오토그래드 소개

오토그래드 : 자동 미분 기능 제공  
파이토치는 requires_grad 속성이 True인 텐서의 연산을 추적하기 위한 계산 그래프를 구축하고, backward 함수가 호출되면 이 그래프를 따라 미분을 자동으로 수행하고 계산된 그래디언트를 채워 놓는다.  

In [8]:
x = torch.FloatTensor([[1,2],
                       [3,4]]).requires_grad_(True)

이렇게 requires_grad 속성이 True인 텐서가 있을 때 이 텐서가 들어간 연산의 결과가 담긴 텐서도 자동으로 requires_grad 속성값을 True로 갖게 된다.

In [9]:
x1 = x + 2
print(x1)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)


In [10]:
x2 = x - 2
print(x2)

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)


In [11]:
x3 = x1 * x2
print(x3)

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)


In [12]:
y = x3.sum()
print(y)

tensor(14., grad_fn=<SumBackward0>)


코드 실행으로 생성된 결과 텐서들이 모두 grad_fn 속성을 갖는다.  
예를들어 x1의 덧셈 연산의 결과물이기 때문에 x1의 grad_fn 속성은 AddBackward0임을 볼 수 있다.  
텐서 y는 sum 함수를 썼으므로 스칼라 값이 되었다. 여기서 다음과 같이 backward 함수를 호출한다.

In [13]:
y.backward()

그러면 x,x1,x2,x3,y 모두 grad속성에 그래디언트 값이 계산되어 저장되었을 것이다.  
이것을 수식으로 나타내면 다음과 같다.

<img src = "오토그래드1.jpg" width = "400" height = "400">

y를 다시 x로 미분하면 다음과 같다.

<img src = "오토그래드2.jpg" width = "300" height = "300">

In [14]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


이 연산에 사용된 텐서들을 배열과 같은 곳에 저장할 경우 메모리 누수의 원인이 되기 때문에 주의해야 한다.  
만약에 x3을 배열 등에 저장해두지 않을 경우 x3뿐만 아니라 계산 그래프에 등록된 텐서들 모두 메모리에서 해제되지 않는다.  
따라서 detach함수를 통해 그래프로부터 떼어낼 수 있다.

In [15]:
x3.detach()

tensor([[-3.,  0.],
        [ 5., 12.]])